/**
 * connector-auth-audit — measures how many catalog connectors are actually
 * connectable, by exercising the real resolution paths rather than asserting
 * counts in prose.
 *
 * Usage: npx ts-node scripts/connector-auth-audit.ts
 */

import { MCP_CATALOG, findCatalogEntry } from '../src/core/mcp/McpCatalog';
import { OAuthConnector, hasKnownOAuthProvider, oauthProviderSlugFor } from '../src/core/mcp/OAuthConnector';
import { curatedConnectorForCatalogId } from '../src/core/mcp/curatedTools';

const oauth = new OAuthConnector();

type State = 'ready' | 'needs_key' | 'needs_oauth_app' | 'needs_setup';

function classify(id: string): State {
  const entry = findCatalogEntry(id);
  const key = entry?.credentialKey || id;
  const hasBaseUrl = Boolean((entry?.baseUrl && entry.baseUrl.trim()) || curatedConnectorForCatalogId(id));

  if (entry?.authType === 'none') return 'ready';
  if (entry?.authType === 'oauth') return hasKnownOAuthProvider(key) ? 'needs_oauth_app' : 'needs_setup';
  return hasBaseUrl ? 'needs_key' : 'needs_setup';
}

function main(): void {
  const counts: Record<State, number> = { ready: 0, needs_key: 0, needs_oauth_app: 0, needs_setup: 0 };
  const oauthCounts = { total: 0, resolve: 0, autoGenerated: 0, unknownProvider: 0 };

  for (const c of MCP_CATALOG) {
    counts[classify(c.id)]++;
    if (c.authType !== 'oauth') continue;
    oauthCounts.total++;
    if (c.id.startsWith('apisguru-')) { oauthCounts.autoGenerated++; continue; }
    try {
      oauth.resolve(c.credentialKey || c.id, { clientId: 'audit' });
      oauthCounts.resolve++;
    } catch {
      oauthCounts.unknownProvider++;
    }
  }

  const curated = MCP_CATALOG.filter(c => curatedConnectorForCatalogId(c.id));

  console.log('Catalog total:            ', MCP_CATALOG.length);
  console.log('');
  console.log('OAuth resolution:');
  console.log('  total oauth connectors: ', oauthCounts.total);
  console.log('  resolve to a provider:  ', oauthCounts.resolve, '(hand-curated)');
  console.log('  auto-generated apisguru:', oauthCounts.autoGenerated, '(resolve via spec ingestion)');
  console.log('  unknown provider:       ', oauthCounts.unknownProvider);
  console.log('');
  console.log('User readiness:');
  console.log('  ready (no auth):        ', counts.ready);
  console.log('  needs an API key:       ', counts.needs_key);
  console.log('  needs an OAuth app:     ', counts.needs_oauth_app);
  console.log('  needs setup (no spec):  ', counts.needs_setup);
  console.log('');
  console.log('Connectors with curated tools: ', curated.length);

  const named = ['productivity-gmail', 'productivity-google-calendar', 'music-audio-spotify',
    'productivity-microsoft-365', 'payments-finance-paypal', 'social-networks-tiktok'];
  console.log('');
  console.log('Spot checks:');
  for (const id of named) {
    const c = findCatalogEntry(id);
    if (!c) { console.log(`  ${id}: NOT IN CATALOG`); continue; }
    let provider = 'n/a';
    try { provider = oauthProviderSlugFor(c.credentialKey || c.id) ?? 'unknown'; } catch { /* ignore */ }
    console.log(`  ${c.name.padEnd(18)} ${classify(id).padEnd(16)} provider=${provider}`);
  }
}

main();
