/**
 * Native Compiler — compiles hot skills into native code via pluggable
 * backends. Ships with a C++ (N-API addon) backend that emits a real,
 * buildable node addon, and a no-op backend for tests/machines without a
 * toolchain.
 *
 * The generated addon is a generic invocation bridge: every native tool is
 * exported as a callable N-API function plus dispatched through `invoke(tool,
 * inputJson)`. Tool functions take a single JSON-string argument and return a
 * JSON-string envelope, so the TypeScript host can load the `.node` artifact
 * and drive any hot skill through a uniform call boundary. Actual skill logic
 * lives in the host (prompt/LLM), but the boundary is a real native module —
 * no more `double _tool(double in){return in;}` placeholder.
 */

import * as fs from 'fs';
import * as path from 'path';
import { NativeArtifact, NativeBackend, CompiledSkill } from './SkillCompiler';
import { getLogger } from '../Logger';

export interface CompilerConfig {
  /** C compiler used to build native addons. */
  cc?: string;
  /** Skip the actual build (emit source only). */
  emitOnly?: boolean;
}

function sanitizeCpp(s: string): string {
  return s.replace(/[^a-zA-Z0-9_]/g, '_');
}

function cppString(s: string): string {
  // Escape for use inside a C++ double-quoted string literal.
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r/g, '').replace(/\n/g, '\\n');
}

export class CppBackend implements NativeBackend {
  readonly language = 'cpp';
  private cc: string;
  private emitOnly: boolean;

  constructor(config: CompilerConfig = {}) {
    this.cc = config.cc ?? 'g++';
    this.emitOnly = config.emitOnly ?? true;
  }

  async compile(skill: CompiledSkill, outDir: string): Promise<NativeArtifact> {
    const safe = sanitizeCpp(skill.name);
    const buildId = `${safe}_${skill.version.replace(/[^a-z0-9_.]/gi, '_')}`;
    const srcPath = path.join(outDir, `${buildId}.cpp`);
    fs.mkdirSync(outDir, { recursive: true });

    const nativeTools = skill.tools.filter(t => t.native);
    const exported = nativeTools.length ? nativeTools : [{ name: 'invoke', description: 'Generic invoke entry' } as const];

    // Per-tool N-API functions + a dispatcher.
    const toolFns = exported
      .map(t => {
        const fn = `Tool_${sanitizeCpp(t.name)}`;
        return `// tool: ${t.name}\n//   ${cppString(t.description)}\nstatic napi_value ${fn}(napi_env env, napi_callback_info info) {\n  std::string in;\n  if (!ReadInput(env, info, in)) {\n    napi_throw_type_error(env, nullptr, "input must be a JSON string");\n    return nullptr;\n  }\n  return MakeEnvelope(env, "${cppString(t.name)}", in);\n}`;
      })
      .join('\n\n');

    const dispatch = exported
      .map(t => `    if (tool == "${cppString(t.name)}") return Tool_${sanitizeCpp(t.name)}(env, info);`)
      .join('\n');

    const source = `// Generated by Umbra Skill Compiler — ${skill.name} v${skill.version}
// Domain: ${skill.domain} | Hot: ${skill.hot} | Memory: ${skill.memorySize}B
// Native tools: ${exported.map(t => t.name).join(', ') || '(none)'}
#include <node_api.h>
#include <cstring>
#include <string>

namespace {

bool ReadInput(napi_env env, napi_callback_info info, std::string& out) {
  size_t argc = 1;
  napi_value argv[1];
  napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr);
  if (argc == 0) { out = "{}"; return true; }
  napi_valuetype t;
  napi_typeof(env, argv[0], &t);
  if (t != napi_string) return false;
  size_t len = 0;
  napi_get_value_string_utf8(env, argv[0], nullptr, 0, &len);
  out.resize(len);
  napi_get_value_string_utf8(env, argv[0], &out[0], len + 1, &len);
  return true;
}

napi_value MakeEnvelope(napi_env env, const std::string& tool, const std::string& input) {
  std::string json = "{\\"tool\\":\\"" + tool + "\\",\\"native\\":true,\\"input\\":" + input + "}";
  napi_value result;
  napi_create_string_utf8(env, json.c_str(), json.size(), &result);
  return result;
}

${toolFns}

// invoke(tool, inputJson) — dispatch to a tool by name.
napi_value Invoke(napi_env env, napi_callback_info info) {
  size_t argc = 2;
  napi_value argv[2];
  napi_get_cb_info(env, info, &argc, argv, nullptr, nullptr);
  if (argc < 1) {
    napi_throw_type_error(env, nullptr, "invoke(tool, inputJson) requires a tool name");
    return nullptr;
  }
  std::string tool;
  {
    size_t len = 0;
    napi_get_value_string_utf8(env, argv[0], nullptr, 0, &len);
    tool.resize(len);
    napi_get_value_string_utf8(env, argv[0], &tool[0], len + 1, &len);
  }
${dispatch}
  napi_throw_type_error(env, nullptr, "unknown tool");
  return nullptr;
}

}  // namespace

napi_value Init(napi_env env, napi_value exports) {
${exported.map(t => `  napi_create_function(env, "${cppString(t.name)}", NAPI_AUTO_LENGTH, Tool_${sanitizeCpp(t.name)}, nullptr, &exports);`).join('\n')}
  napi_create_function(env, "invoke", NAPI_AUTO_LENGTH, Invoke, nullptr, &exports);
  return exports;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
`;
    fs.writeFileSync(srcPath, source, 'utf8');

    // Emit the node-gyp manifest so the artifact is buildable with
    // `node-gyp rebuild` (or the direct cc invocation below).
    const gyp = `{
  "targets": [
    {
      "target_name": "${safe}",
      "sources": ["${path.basename(srcPath)}"],
      "cflags_cc": ["-std=c++17"],
      "xcode_settings": { "CLANG_CXX_LANGUAGE_STANDARD": "c++17" }
    }
  ]
}
`;
    fs.writeFileSync(path.join(outDir, 'binding.gyp'), gyp, 'utf8');

    const artifact: NativeArtifact = {
      language: 'cpp',
      entry: 'invoke',
      sourcePath: srcPath,
      buildId,
    };

    if (!this.emitOnly) {
      try {
        this.build(srcPath, path.join(outDir, `${buildId}.node`));
      } catch (err) {
        getLogger().warn({ err, skill: skill.name }, 'Native build failed; source emitted only');
      }
    }
    return artifact;
  }

  private build(srcPath: string, outPath: string): void {
    const { execSync } = require('child_process') as typeof import('child_process');
    // Preferred: node-gyp (handles N-API include dirs + linking correctly).
    try {
      execSync(`node-gyp rebuild --directory "${path.dirname(srcPath)}"`, { stdio: 'pipe' });
      return;
    } catch {
      // Fall back to a direct compile using Node's bundled headers. Only
      // meaningful on POSIX-ish toolchains (g++/clang); MSVC needs the
      // full /I + node.lib set that node-gyp supplies.
      const nodeInc = require('process').execPath
        ? path.join(path.dirname(require('process').execPath), '..', 'include', 'node')
        : '';
      const include = fs.existsSync(nodeInc) ? `-I"${nodeInc}"` : '';
      execSync(`"${this.cc}" -shared -fPIC ${include} -o "${outPath}" "${srcPath}"`, { stdio: 'pipe' });
    }
  }
}

/** Backend that records compilation intent without producing binaries. */
export class NoopBackend implements NativeBackend {
  readonly language = 'noop';

  async compile(skill: CompiledSkill, outDir: string): Promise<NativeArtifact> {
    return {
      language: 'noop',
      entry: 'invoke',
      sourcePath: path.join(outDir, `${skill.name}.noop`),
      buildId: `${skill.name}-${skill.version}`,
    };
  }
}
