import * as fs from 'fs';
import * as path from 'path';
import { getLogger } from '../../core/Logger';

export class TopicIndexer {
  private topicsDir: string;
  private journalDir: string;

  constructor(baseDir: string) {
    this.topicsDir = path.join(baseDir, 'topics');
    this.journalDir = path.join(baseDir, 'journal');
  }

  initialize(): void {
    if (!fs.existsSync(this.topicsDir)) fs.mkdirSync(this.topicsDir, { recursive: true });
  }

  rebuildIndex(): void {
    const topicFiles = this.getTopicFiles();
    const indexPath = path.join(this.topicsDir, 'index.md');

    const content = `# Topics Index

Browse journal entries by topic.

## All Topics

${topicFiles.map(f => {
  const name = f.replace(/\.md$/, '');
  const displayName = name.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  return `  - [[topics/${name}|${displayName}]]`;
}).join('\n')}

---

*Auto-generated by Umbra OS Topic Indexer.*
`;

    fs.writeFileSync(indexPath, content, 'utf-8');
    getLogger().info({ topics: topicFiles.length }, 'Topic index rebuilt');
  }

  getTopicFiles(): string[] {
    try {
      return fs.readdirSync(this.topicsDir).filter(f => f.endsWith('.md') && f !== 'index.md');
    } catch {
      return [];
    }
  }

  getJournalDates(): string[] {
    const dates: string[] = [];
    this.walkForDates(this.journalDir, dates);
    return dates.sort().reverse();
  }

  private walkForDates(dir: string, results: string[]): void {
    try {
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const e of entries) {
        const full = path.join(dir, e.name);
        if (e.isDirectory()) this.walkForDates(full, results);
        else if (e.name.endsWith('.md') && !e.name.endsWith('index.md')) {
          results.push(e.name.replace(/\.md$/, ''));
        }
      }
    } catch { }
  }
}
